//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyatochka.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Product = new HashSet<Product>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public int CountryId { get; set; }
        public string Address { get; set; }
        public string DirectorFirstName { get; set; }
        public string DirectorLastName { get; set; }
        public string DirectorMiddleName { get; set; }
        public long DirectorPhone { get; set; }
        public int DirectorPassport { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
