//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyatochka.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductCost = new HashSet<ProductCost>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Compound { get; set; }
        public float Weight { get; set; }
        public int WeightTypeId { get; set; }
        public string ExpirationDate { get; set; }
        public string ConditionsOfContain { get; set; }
        public long BrandId { get; set; }
        public int ProductCategoryId { get; set; }
        public int CountryOfOriginId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Country Country { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual WeightType WeightType { get; set; }
        public virtual ICollection<ProductCost> ProductCost { get; set; }
    }
}
