//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyatochka.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCost
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public float DefaultCost { get; set; }
        public Nullable<short> Discount { get; set; }
        public Nullable<int> DiscountTypeId { get; set; }
    
        public virtual DiscountType DiscountType { get; set; }
        public virtual Product Product { get; set; }
    }
}
